#!/bin/bash 

#
# extract data for candidiate pixels 
# 

threshold="0.6"
region="11100/13500/10750/11250"
reg="11100/13500/10750/11250"
gmt grdmath scatter.grd $threshold LT 0 NAN scatter.grd MUL = cands0.grd 

gmt grdsample -T cands0.grd -R$region -Gcands.grd 
cp cands.grd cands_old.grd 
gmt grdedit cands.grd -R$reg 

input="cands.grd"
width=`gmt grdinfo -C $input | awk '{print $10}'`
echo $width > width.txt # range
length=`gmt grdinfo -C $input | awk '{print $11}'`
echo $length > len.txt # azimuth

# Get the dispersion index for PS candidates
gmt grd2xyz cands.grd -s > cands.dat 
gmt gmtconvert cands.dat -o2 > pscands.1.da
awk '{printf("%d %d %d\n", NR,$2,$1)}' cands.dat > pscands.1.ij

# Retrieve lon/lat for PS candidates
gmt grd2xyz cands_old.grd -s > cands_old.dat 
proj_ra2ll_ascii.csh trans.dat cands_old.dat cands.ll.dat
rm ralt.grd raln.grd 
gmt gmtconvert cands.ll.dat -o0,1 -bos > pscands.1.ll

# Retrieve hgt for PS candidates
gmt grdtrack cands.ll.dat -Gdem.grd -Z -nb -bos > pscands.1.hgt 

# Retrieve look angles
gmt grdsample cands_old.grd -I50+/50+ -Gtmp.grd 
gmt grd2xyz tmp.grd | awk '{print $1,$2,1}' > tmp.xy
proj_ra2ll_ascii.csh trans.dat tmp.xy tmp.ll 
#rm ralt.grd raln.grd 
awk '{printf("%f %f %d\n%f %f %d\n",$1,$2,0,$1,$2,1000)}' tmp.ll > tmp.llt
ln -s ../topo/master.PRM .
SAT_look master.PRM < tmp.llt > tmp.lltn 
gmt gmtmath -C5 -o5 tmp.lltn ACOS 180 MUL PI DIV = look_angle.1.in
awk '{printf("%0.4f\n", $1)}' look_angle.1.in > look_angle0.1.in
rm look_angle.1.in
mv look_angle0.1.in look_angle.1.in
rm tmp.xy tmp.ll tmp.llt tmp.lltn

# Retrieve perpendicular baseline for each interferogram
# copy the calculation from PS folder
cp ../../bperp* .

# Retrieve phase for PS candidates
rm pscands.1.ph
cat list_sbas | while read name prm_master prm_slave date_master date_slave
do
  gmt grdtrack cands_old.dat -Gre_$name.grd -Z -bos >> pscands.1.ph
  gmt grdtrack cands_old.dat -Gim_$name.grd -Z -bos >> pscands.1.ph
done

rm cands_old.grd 
