#!/bin/bash

# NI, 08.02.2018 (noorlaila@geodesy.its.ac.id)
# mt_prep gmtsar for SBAS configuration

############ set parameters ################################################
region="9000/12000/7000/8000"
R=3
A=2
ov_R=50
ov_A=200
crop=/home/isya/APPS/ciloto/Sentinel1/batch_dsc/stack/crop
threshold="0.5"
raw=/home/isya/APPS/ciloto/Sentinel1/batch_dsc/raw
raw_orig=/home/isya/APPS/ciloto/Sentinel1/batch_dsc/raw_orig
topo=/home/isya/APPS/ciloto/Sentinel1/batch_dsc/topo
SLC=/home/isya/APPS/ciloto/Sentinel1/batch_dsc/raw
heading=-1.6799e+02 # for descending, for ascending: -12.00707218611660e
master_date=20160717
############################################################################

# file input (must be put on PS folder):
# 		date_no_master.txt
#		intf_list.in

rm -r -f SMALL_BASELINES patch_reg cands_*
mkdir patch_reg
cd patch_reg
devide_region.sh $region $R $A $ov_R $ov_A
cd ..

mkdir SMALL_BASELINES
cd SMALL_BASELINES
matlab -nojvm -nosplash -nodisplay < $STAMPS/matlab/sb_parms_initial.m > sb_parms_initial.log
cd ..
rm -r -f SMALL_BASELINES/PATCH_*

p=1
while read region
do

  mt_extract_info_gmtsar_sbas $raw $raw_orig $topo $SLC $heading $master_date
  mt_extract_cands_gmtsar_sbas $crop $threshold $region

  mkdir -p cands_$p
  mv cands_old.grd cands_"$p"/.
  mv cands0.grd cands_"$p"/.
  mv cands.grd cands_"$p"/.

  patch=$(echo PATCH_$p)
  mkdir SMALL_BASELINES/$patch
  mv pscands* SMALL_BASELINES/$patch/.
  ln -s -f $PWD/ifgday.1.in SMALL_BASELINES/$patch/.
  cd SMALL_BASELINES/$patch
  correct_forum_sbas
  cd ../..
  (( p++ ))
done < patch_reg/PATCH.loc

rsync -av patch_reg/PATCH_* SMALL_BASELINES/.
cp patch_reg/width.txt SMALL_BASELINES/.
cp patch_reg/len.txt SMALL_BASELINES/.
cd SMALL_BASELINES
ln -f -s ../*.in .
ls -d PATCH_* > patch.list
cd ..

